### ISSUE TITLE
Request to Cite Our ICML2023 Poster Paper in IPL

### ISSUE THREAD

**Issue by yachenkang** [jhejna/inverse-preference-learning#1]
A very interesting piece of work!

We would like to kindly request that you consider adding our paper titled [Beyond Reward: Offline Preference-guided Policy Optimization](https://openreview.net/forum?id=0BgDXE6vJJ), which has been officially published at ICML2023 as poster paper, to the references of the subsequent modified version of IPL.

We believe that the two works share similar problem settings, as both attempt to remove the reinforcement learning process in the PbRL framework. Although the implementation methods of the two papers are not exactly the same, we still believe that citing our paper will make IPL more rigorous, especially considering that this is still a developing field.

We hope you will seriously consider our request.

```
@article{kang2023beyond,
  title={Beyond reward: Offline preference-guided policy optimization},
  author={Kang, Yachen and Shi, Diyuan and Liu, Jinxin and He, Li and Wang, Donglin},
  journal={arXiv preprint arXiv:2305.16217},
  year={2023}
}
```

**Comment by jhejna** [comment]
Hi!

Thanks for making us aware! I actually saw your paper at ICML, but we had already published our paper on ArXiv by then. We have included a citation in the updated version. 

Feel free to reach out via email if you have other questions!
