### ISSUE TITLE
The ensembleMLP used in IPL-IQL algo value calculation

### ISSUE THREAD

**Issue by RZ-Q** [jhejna/inverse-preference-learning#2]
Does this ensembleMLP perform as the same character as the ensemble reward models in normal PbRL?
Thanks for your paper and codes.

**Comment by jhejna** [comment]
EnsembleMLP supports ensemble size of one or more. I wrote the code this way to be maximally flexible. In practice, I use ensemble size of 1 for the value and reward function, as is consistent with other works in offline PbRL. In online PbRL, an ensemble of reward functions is used to estimate uncertainty for selecting new queries, but we don't do that in offline PbRL so I didn't ensemble the reward function. 

See: https://github.com/jhejna/inverse-preference-learning/blob/main/configs/metaworld/mr_iql.yaml#L31 where nothing except the Q function is ensembled.

**Comment by RZ-Q** [comment]
Thanks for your explaination!
